# Generated by Django 4.2.11 on 2025-01-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    # operations = [
    #     migrations.DeleteModel(
    #         name='Sale',
    #     ),
    # ]
