# Generated by Django 4.2.11 on 2025-01-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_user_userprofile_sale'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='inventory_order',
        ),
    ]
