# Generated by Django 4.2.11 on 2025-01-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_order_table'),
        ('inventory', '0005_create_order_model'),
    ]

    operations = [
    ]
