# Generated by Django 4.2.11 on 2025-01-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_product_low_stock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
